### ISSUE TITLE
Cannot find module 'caniuse-db'  'babel-runtime'

### ISSUE THREAD

**Issue by showzyl** [jlengstorf/learn-rollup#28]
**in branch part-3-starter**

Starting LiveReload v0.6.2 for /Users/showzyl/Desktop/test/learn-rollup/build on port 35729.
bundling...
node_modules/nan
resolve failed:  { Error: Cannot find module 'caniuse-db'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.requireRelative.resolve (/Users/showzyl/Desktop/test/learn-rollup/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/showzyl/Desktop/test/learn-rollup/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/Users/showzyl/Desktop/test/learn-rollup/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /Users/showzyl/Desktop/test/learn-rollup/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/Users/showzyl/Desktop/test/learn-rollup/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/Users/showzyl/Desktop/test/learn-rollup/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/Users/showzyl/Desktop/test/learn-rollup/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:571:32) code: 'MODULE_NOT_FOUND' } caniuse-db
resolve failed:  { Error: Cannot find module 'babel-runtime'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.requireRelative.resolve (/Users/showzyl/Desktop/test/learn-rollup/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/showzyl/Desktop/test/learn-rollup/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/Users/showzyl/Desktop/test/learn-rollup/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /Users/showzyl/Desktop/test/learn-rollup/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/Users/showzyl/Desktop/test/learn-rollup/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/Users/showzyl/Desktop/test/learn-rollup/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/Users/showzyl/Desktop/test/learn-rollup/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:571:32) code: 'MODULE_NOT_FOUND' } babel-runtime
bundled in 1951ms. Watching for changes...

**Comment by jlengstorf** [comment]
@showzyl If the module is missing, I'd try running `npm install` again.

If that doesn't work, sometimes it helps to clear the `npm` cache and start over:

```sh
# remove all modules
rm -rf node_modules/

# make sure Node is pulling fresh copies from the server
npm cache clean

# reinstall everything
npm install
```

If that doesn't work, please share the repo you're working in so I can take a look.

**Comment by jlengstorf** [comment]
I just ran the following:

```
git clone git@github.com:jlengstorf/learn-rollup.git --branch part-3-starter
cd learn-rollup/
npm install
```

No errors, and everything works as expected. Closing this issue.
